crud/Student-CRUD/crud/urls.py
from django.urls import include, path
from django.contrib import admin
from student import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', views.StudentList.as_view(), name='student_list'),
    path('new/', views.StudentCreate.as_view(), name='student_new'),
    path('<int:pk>/edit/', views.StudentUpdate.as_view(), name='student_edit'),
    path('<int:pk>/delete/', views.StudentDelete.as_view(), name='student_delete'),
]

crud/Student-CRUD/student/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.StudentList.as_view(), name='student_list'),
    path('new/', views.StudentCreate.as_view(), name='student_new'),
    path('<int:pk>/edit/', views.StudentUpdate.as_view(), name='student_edit'),
    path('<int:pk>/delete/', views.StudentDelete.as_view(), name='student_delete'),
]

crud/Student-CRUD/student/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

  
GENDER_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female')
)

KNOWN_LANGUAGES =( 
    ("1", "Tamil"), 
    ("2", "English"), 
    ("3", "Hindi") 
) 

CITY_CHOICES =( 
    ("1", "Tirupur"), 
    ("2", "Coimbatore"), 
    ("3", "Chennai") 
) 

STATE_CHOICES =( 
    ("1", "TamilNadu"), 
    ("2", "Karnataka"), 
    ("3", "Kerala"),
    ("4", "Andhra Pradesh") 
) 

class Student(models.Model):
    name = models.CharField(max_length= 50,editable=True)
    dateofbirth = models.DateField(default=timezone.now)
    emailid = models.EmailField((""), max_length=254,default="example@gmail.com",editable=True)
    mobile = models.CharField(max_length=10, unique=True,default="9123456789",editable=True)
    gender = models.CharField(choices=GENDER_CHOICES, default="Male",max_length=128,editable=True)
    address = models.TextField(max_length=200,default="Tirupur",editable=True)
    city=models.CharField(max_length=200,choices=CITY_CHOICES,default="Tirupur")
    state=models.CharField(max_length=20,choices=STATE_CHOICES,editable=True,default="Tamil Nadu")
    pincode = models.CharField(("pincode"), max_length=6, default="641604",editable=True)
     

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('student:student_edit', kwargs={'pk': self.pk})

crud/Student-CRUD/student/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from student.models import Student

class StudentList(ListView):
    model = Student

class StudentCreate(CreateView):
    model = Student
    fields = ('name','dateofbirth','emailid','mobile','gender','address','city','state','pincode',)
    success_url = reverse_lazy('student:student_list')

class StudentUpdate(UpdateView):
    model = Student
    fields = ('name','dateofbirth','emailid','mobile','gender','address','city','state','pincode')
    success_url = reverse_lazy('student:student_list')

class StudentDelete(DeleteView):
    model = Student
    success_url = reverse_lazy('student:student_list')

crud/Student-CRUD/student/templates/student/student_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <title>Delete Record</title>
  </head>
  <style>
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: Black;
  }
  li {
    float: left;}
  li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}  li a:hover, .dropdown:hover .dropbtn {
    background-color: #dd2163;
}  .dropdown-content a {
    color: black;
    padding: 2px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}/* General */  h1,h2,h3,h4,h5,h6 {
  font-family: "Libre Franklin", sans-serif;
  font-weight: bold;
}  a {
  color: red;
}  .learn_more-link {
  display: block;
  position: relative;
  border: 8px solid black;
}  .learn_more-link:hover {
  background: rgba(221, 33, 99, 0.75);
  transition: all ease 0.5s;
  -webkit-transition: all ease 0.5s;
  -moz-transition: all ease 0.5s;
}  .learn_more img {
  opacity: .33;
}  .learn_more-text {
  text-align: left;
  position: absolute;
  top: 50%;
  left: 5%;
  transform: translate(-50%, -50%);
  font-size: 2rem;
}  @media (max-width: 7px) {    .learn_more-item {
    margin: 0 0 10rem;
  }  .learn_more {
    margin-bottom: 10rem;
  }
}.dropdown-content a:hover {background-color: #f1f1f1}.dropdown:hover .dropdown-content {
    display: block;
}</style>
<body>
    <ul>
    <li><a href="{% url 'student:student_list' %}" class="learn_more-link">Home</a></li>
    </ul><br>
    <form method="post">{% csrf_token %}
      <h3>Are you sure you want to delete "{{ object }}" ?</h3><br><br>
      <button type="Delete" name="Delete" value="Delete" class="btn btn-warning">Delete</button>
    </form>
    </body>
</html>

crud/Student-CRUD/student/templates/student/student_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title>Modify Students</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
    />
  </head>
  <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: Black;
    }
    li {
      float: left;
    }
    li a,
    .dropbtn {
      display: inline-block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }
    li a:hover,
    .dropdown:hover .dropbtn {
      background-color: #dd2163;
    }
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: red;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
      z-index: 1;
    }
    .dropdown-content a {
      color: black;
      padding: 2px 16px;
      text-decoration: none;
      display: block;
      text-align: left;
    } /* General */
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Libre Franklin", sans-serif;
      font-weight: bold;
    }
    a {
      color: red;
    }
    .learn_more-link {
      display: block;
      position: relative;
      border: 8px solid black;
    }
    .learn_more-link:hover {
      background: rgba(221, 33, 99, 0.75);
      transition: all ease 0.5s;
      -webkit-transition: all ease 0.5s;
      -moz-transition: all ease 0.5s;
    }
    .learn_more img {
      opacity: 0.33;
    }
    .learn_more-text {
      text-align: left;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      font-size: 2rem;
    }
    @media (max-width: 7px) {
      .learn_more-item {
        margin: 0 0 10rem;
      }
      .learn_more {
        margin-bottom: 10rem;
      }
    }
    .dropdown-content a:hover {
      background-color: #f1f1f1;
    }
    .dropdown:hover .dropdown-content {
      display: block;
    }
  </style>
  <body>
    <ul>
      <li>
        <a href="{% url 'student:student_list' %}" class="learn_more-link"
          >Home</a
        >
      </li>
    </ul>
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <h2>Modify Details of the Student</h2>
        <br />
        {{form}}
        <button
          type="submit"
          name="button"
          value="Submit"
          class="btn btn-warning"
        >
          Submit
        </button>
      </form>
    </div>
  </body>
</html>

crud/Student-CRUD/student/templates/student/student_list.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <title>Students Registration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">

  </head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 50;
    overflow: auto;
    background-color: black;
}li {
    float: left;
}li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}li a:hover, .dropdown:hover .dropbtn {
    background-color: #dd2163;
}.dropdown-content a {
    color: black;
    padding: 2px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}/* General */h1,h2,h3,h4,h5,h6 {
  font-family: "Libre Franklin", sans-serif;
  font-weight: bold;
}a {
  color: red;
}.learn_more-link {
  display: block;
  position: relative;
  border: 8px solid black;
}.learn_more-link:hover {
  background: rgba(221, 33, 99, 0.75);
  transition: all ease 0.5s;
  -webkit-transition: all ease 0.5s;
  -moz-transition: all ease 0.5s;
}.learn_more img {
  opacity: .33;
}.learn_more-text {
  text-align: center;
  position: center;
  top: 50%;
  left: 15%;
  transform: translate(-50%, -50%);
  font-size: 2rem;
}@media (max-width: 7px) {
  .learn_more-item {
    margin: 0 0 10rem;
  }
  .learn_more {
    margin-bottom: 10rem;
  }
}.dropdown-content a:hover {background-color: #f1f1f1}.dropdown:hover .dropdown-content {
    display: block;
}</style>
  <body>
    <ul>
      <li><a href="{% url 'student:student_list' %}" class="learn_more-link">Home</a></li>
      </li>
    </ul>
    <div class="container">
      <br>
      <a href="{% url 'student:student_new' %}"class="btn btn-primary" role="button">Add Student</a><br><br>
      <table class="table" border="20px">
        <thead>
          <tr>
            <th>Name </th>
            <th>dateofbirth </th>
            <th>emailid </th>
            <th>mobile </th>
            <th>gender </th>
            <th>address </th>
            <th>city </th>
            <th>state </th>
            <th>pincode </th>
          
          </tr>
        </thead>
        <tbody>
          {% for student in object_list %}
          <tr>
            <td>{{ student.name }}</td>
            <td>{{ student.dateofbirth }}</td>
            <td>{{ student.emailid }}</td>
            <td>{{ student.mobile }}</td>
            <td>{{ student.gender }}</td>
            <td>{{ student.address }}</td>
            <td>{{ student.city }}</td>
            <td>{{ student.state }}</td>
            <td>{{ student.pincode }}</td>
            
            <th>
              <a href="{% url 'student:student_edit' student.id %}" class="btn btn-warning" role="button">Edit</a>
              <a href="{% url 'student:student_delete' student.id %}" class="btn btn-danger" role="button">Delete</a>
            </th>
            </tr>
        {% endfor %}
  </body>
</html>